### ISSUE TITLE
Gráfica de líneas tiene un comportamiento extraño en vista móvil. 

### ISSUE THREAD

**Issue by luiscolungaperez** [salsa-community/sisdai-graficas#55]
Buen día, tengo un problema de visualización con la gráfica de líneas cuando estoy en la vista movil.

Problemas
- Internamente en el componente hay una etiqueta con la clase "rotation-wrapper-outer" que rompe el modelo de caja y hace que la vista se rompa y tenga un scroll horizontal.

**Comment by jdanielgoh** [comment]
Lo voy revisando. Gracias :)

**Comment by luiscolungaperez** [comment]
![image](https://github.com/salsa-community/sisdai-graficas/assets/66395776/89d8111c-2521-4490-84cc-95a775002e88)


este es la etiqueta que suele salirse en la vista movil

**Comment by jdanielgoh** [comment]
@luiscolungaperez , Puedes reinstalar la biblioteca y probar si ya se resolvió el bug ? es probable que se tengan que ajustar los márgenes de algunas gráficas, porque este era un error que estaba latente no sólo en líneas, sino en todas las gráficas con ejes. LA última versión es la v2.0.2. Saludos!!

**Comment by luiscolungaperez** [comment]
@jdanielgoh Disculpa, ya actualicé la librería a la versión que me comentaste, pero aún persiste el mismo error del margen de la gráfica

**Comment by jdanielgoh** [comment]
@luiscolungaperez que raro :/. Puedes verificar que los ejes, especialmente en el de lineas ya no tenga la clase "rotation-wrapper-outer", y mas bien tenga solo la clase "contenedor-titulo-eje-y" ?

**Comment by luiscolungaperez** [comment]
@jdanielgoh ya revisé lo que comentaste, pero sigue teniendo la clase "rotation-wrapper-outer"

**Comment by jdanielgoh** [comment]
Gracias @luiscolungaperez ! creo que entonces no se ha instalado la ultima versión. Podrias intentar  reinstalar pero antes borrar tu cache ? a mí me funciona borrar la carpeta de node_modules y el package-lock  y despues volver a instalar todo  asegurandonos de tener  la versión correcta de sisdai-graficas, puedes usar esta linea en el package.json `"sisdai-graficas": "github:salsa-community/sisdai-graficas#v2.0.2"` para especificar la versión

**Comment by luiscolungaperez** [comment]
Hola @jdanielgoh ya realicé el proceso como tú comentas, pero la clase persiste
Ya eliminé

- node_modules
- yarn.lock (porque utilizo yarn)
- elimine e instale la versión de la dependencia v2.0.2

**Comment by jdanielgoh** [comment]
Vale, gracias! seguiré revisando entonces :)

**Comment by jdanielgoh** [comment]
Hola de nuevo, @luiscolungaperez . Podrías hacer una prueba con  la versión v2.0.3 ? Ya lo probé en mi local en cuencas y ya no veo el error

**Comment by jdanielgoh** [comment]
quizá se deban hacer algunos ajustes en lo márgenes 🔢 :e
